apiVersion: v1
kind: Service
metadata:
  name: front-back-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: front
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: back
  selector:
    app: front
